<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class GuruSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nip'            => '196512101990031005',
                'nama'           => 'Drs. Slamet Widodo, M.Pd.',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'Pati',
                'tanggal_lahir'  => '1965-12-10',
                'jabatan'        => 'Kepala Sekolah',
                'mata_pelajaran' => 'IPS',
                'no_telepon'     => '081234567001',
                'alamat'         => 'Jl. Raya Margoyoso No. 15, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '197003151998022003',
                'nama'           => 'Sri Mulyani, S.Pd.',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'Kudus',
                'tanggal_lahir'  => '1970-03-15',
                'jabatan'        => 'Wakil Kepala Sekolah',
                'mata_pelajaran' => 'Bahasa Indonesia',
                'no_telepon'     => '081234567002',
                'alamat'         => 'Ds. Bulumanis Kidul RT 03/02, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '198107202006041012',
                'nama'           => 'Ahmad Fauzi, S.Pd.',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'Pati',
                'tanggal_lahir'  => '1981-07-20',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'Matematika',
                'no_telepon'     => '082345678003',
                'alamat'         => 'Ds. Sekarjalak RT 01/03, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '197805122003122004',
                'nama'           => 'Endang Purwati, S.Pd.',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'Jepara',
                'tanggal_lahir'  => '1978-05-12',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'IPA',
                'no_telepon'     => '085678901004',
                'alamat'         => 'Jl. P. Sudirman No. 23, Kec. Tayu, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '198509082010011008',
                'nama'           => 'Rizky Pratama, S.Pd.',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'Semarang',
                'tanggal_lahir'  => '1985-09-08',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'Bahasa Inggris',
                'no_telepon'     => '087890123005',
                'alamat'         => 'Ds. Ngemplak Kidul RT 02/01, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '197411302000032006',
                'nama'           => 'Siti Nurjanah, S.Ag.',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'Pati',
                'tanggal_lahir'  => '1974-11-30',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'Pendidikan Agama Islam',
                'no_telepon'     => '081345678006',
                'alamat'         => 'Ds. Cebolek Kidul RT 04/02, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '198203172008041007',
                'nama'           => 'Teguh Wahyudi, S.Pd.',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'Blora',
                'tanggal_lahir'  => '1982-03-17',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'PJOK',
                'no_telepon'     => '089012345007',
                'alamat'         => 'Ds. Purworejo RT 01/04, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '198806252012042008',
                'nama'           => 'Dewi Kartika Sari, S.Pd.',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'Pati',
                'tanggal_lahir'  => '1988-06-25',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'Seni Budaya',
                'no_telepon'     => '082456789008',
                'alamat'         => 'Ds. Waturoyo RT 03/01, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '197609142001031009',
                'nama'           => 'Bambang Hermanto, S.Pd.',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'Rembang',
                'tanggal_lahir'  => '1976-09-14',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'PKn',
                'no_telepon'     => '085678012009',
                'alamat'         => 'Jl. Jend. Sudirman No. 8, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '199001032015022010',
                'nama'           => 'Rina Agustina, S.Pd.',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'Demak',
                'tanggal_lahir'  => '1990-01-03',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'Prakarya',
                'no_telepon'     => '087890234010',
                'alamat'         => 'Ds. Kajen RT 02/03, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '198412182009041011',
                'nama'           => 'Hendra Kurniawan, S.Kom.',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'Pati',
                'tanggal_lahir'  => '1984-12-18',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'Informatika',
                'no_telepon'     => '081234890011',
                'alamat'         => 'Ds. Tengklik RT 01/02, Kec. Tayu, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '197202281999032012',
                'nama'           => 'Nurul Hidayah, S.Pd.',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'Kudus',
                'tanggal_lahir'  => '1972-02-28',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'Bahasa Jawa',
                'no_telepon'     => '082345012012',
                'alamat'         => 'Ds. Bulumanis Lor RT 05/01, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '198708102011041013',
                'nama'           => 'Yoga Aditya, S.Pd.',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'Pati',
                'tanggal_lahir'  => '1987-08-10',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'IPS',
                'no_telepon'     => '089012567013',
                'alamat'         => 'Ds. Margotuhu Kidul RT 03/02, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '199203142018022014',
                'nama'           => 'Putri Rahmawati, S.Pd.',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'Jepara',
                'tanggal_lahir'  => '1992-03-14',
                'jabatan'        => 'Guru',
                'mata_pelajaran' => 'Matematika',
                'no_telepon'     => '085678345014',
                'alamat'         => 'Ds. Pangkalan RT 02/04, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'nip'            => '198001052005011015',
                'nama'           => 'Agus Supriyanto, S.Pd.',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'Pati',
                'tanggal_lahir'  => '1980-01-05',
                'jabatan'        => 'Guru BK',
                'mata_pelajaran' => 'Bimbingan Konseling',
                'no_telepon'     => '087890678015',
                'alamat'         => 'Ds. Sekarjalak RT 04/01, Kec. Margoyoso, Kab. Pati',
                'foto'           => null,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
        ];

        // Hapus data test sebelumnya & insert data baru
        $this->db->table('guru')->truncate();
        $this->db->table('guru')->insertBatch($data);
    }
}
